export const types = {
  PRELOADER_ON: "PRELOADER_ON",
  PRELOADER_OFF: "PRELOADER_OFF",
  FETCH_USERS_REQUEST: "FETCH_USERS_REQUEST",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",
};
